# Generated by Django 2.0.2 on 2018-09-03 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/avatar/')),
                ('social_twitter', models.CharField(blank=True, max_length=128, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=128, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=128, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='academy.Author')),
                ('category', models.ManyToManyField(to='academy.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('file', models.CharField(max_length=512)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'ordering': ('track_no',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/slider/')),
                ('file', models.FileField(max_length=512, upload_to='')),
                ('link', models.URLField()),
                ('link_title', models.CharField(default='Learn more', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='coursefile',
            name='likes',
            field=models.ManyToManyField(to='academy.Like'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='views',
            field=models.ManyToManyField(to='academy.View'),
        ),
        migrations.AddField(
            model_name='course',
            name='files',
            field=models.ManyToManyField(to='academy.CourseFile'),
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(to='academy.Like'),
        ),
        migrations.AddField(
            model_name='course',
            name='rank',
            field=models.ManyToManyField(to='academy.Rank'),
        ),
        migrations.AddField(
            model_name='course',
            name='software',
            field=models.ManyToManyField(to='academy.Software'),
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.ManyToManyField(to='academy.View'),
        ),
    ]
