# Generated by Django 2.0.2 on 2018-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AlterField(
            model_name='slider',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/slider/'),
        ),
    ]
