# Generated by Django 2.0.2 on 2018-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20180903_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_file'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rank/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='software',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='software/'),
        ),
    ]
