# Generated by Django 2.0.2 on 2018-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20180903_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='likes',
            field=models.ManyToManyField(blank=True, to='academy.Like'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='views',
            field=models.ManyToManyField(blank=True, to='academy.View'),
        ),
    ]
